### ISSUE TITLE
Corrigir mensagem na tela "Lançamento de notas"

### ISSUE THREAD

**Issue by VitorAless** [tarley/pro300#12]
Ao informar um número de pessoas do grupo menor que o mínimo o sistema exibe a seguinte mensagem: "Quantidade mínina de pessoas por grpo inválida." - Corrigir de 'grpo' para 'grupo' com teste feito no ambiente de produção: dia 28/11/2016 12:35

**Comment by Frazoni** [comment]
Resolvido.

**Comment by andrescarvalho** [comment]
Teste feito na versão publicada hoje, 06/12 pelo Tarley. 
Texto ainda está errado, ver anexo:

![p300_teste_lancamentonotas](https://cloud.githubusercontent.com/assets/18200701/20929057/a44c014c-bbaf-11e6-9a94-2fbddb50d5d0.jpg)

**Comment by fillipeperpetuo** [comment]
Resolvido, subi correção.
