### ISSUE TITLE
Melhoria: Na tela Gestão de Grupos

### ISSUE THREAD

**Issue by VitorAless** [tarley/pro300#16]
Melhoria: Na tela Gestão de Grupos, quando não há nenhum grupo cadastrado, o sistema poderia exibir o seguinte texto: Nenhum grupo cadastrado. Teste feito no ambiente de produção: dia 24/11/2016 20:15

**Comment by katernets** [comment]
Não havendo nada a mostra não há necessidade de uma mensagem para informar algo que já é visual.
