### ISSUE TITLE
Alterar senha

### ISSUE THREAD

**Issue by napolianasl** [tarley/pro300#19]
o campo de alterar senha dá opção de utilizar senhas de  emails que já foram digitado anteriormente
é uma melhoria!
obrigada

![image](https://cloud.githubusercontent.com/assets/18200760/20899981/ad3c9434-bb13-11e6-9978-42aa418d2bb0.png)

**Comment by fillipeperpetuo** [comment]
Isso é uma função do próprio navegador, se você deixa configurado pra salvar emails e senha, histórico de formulários, consequentemente vai sugerir, se limpar, não vai sugerir mais
![capturar](https://cloud.githubusercontent.com/assets/17915597/20952349/f5b45440-bc12-11e6-8f1d-d25d794b2550.PNG)
.
