### ISSUE TITLE
Tela de Cadastro / Editar Cadastro

### ISSUE THREAD

**Issue by andrescarvalho** [tarley/pro300#23]
O sistema não limita a quantidade máxima de caracteres para o campo Nome. 

Mesmo que o banco de dados permita qualquer quantidade de caracteres para este campo (o que também está errado), quando o usuário informa um texto muito grande, o layout da tela fica desconfigurado.

Ver anexo.

![teste_p300](https://cloud.githubusercontent.com/assets/18200701/20906650/51270266-bb30-11e6-83a8-1a51aa56fda8.jpg)

**Comment by vivianhsilva** [comment]
Resolvido.

**Comment by andrescarvalho** [comment]
Mesmo limitando a quantidade de caracteres o layout ainda apresenta quebra, por favor verificar. 

![p300_teste0612](https://cloud.githubusercontent.com/assets/18200701/20928838/be734310-bbae-11e6-9938-51ffc080b76f.png)

**Comment by fillipeperpetuo** [comment]
Alteração no cadastro e edição de professor realizadas no nome, layout só vai quebrar se for digitado uma palavra com os caracteres tudo, como sobrenome não é uma palavra gigantesca, funciona olha:

![Uploading Capturar.PNG…]()
