### ISSUE TITLE
Tela Editar Atividade

### ISSUE THREAD

**Issue by andrescarvalho** [tarley/pro300#26]
Ao entrar na tela Editar Atividade e depois clicar em Cancelar, o sistema não redireciona para a tela anterior permanecendo na tela de edição, ou seja, botão cancelar está sem ação.

Passos para reproduzir:
1 - Acessoar o sistema P300 com perfil de professor. 
2 - Clicar no menu "Administrar Atividades"
3 - Na tela Atividades, clicar no botão Editar em alguma atividade da lista. 
4 - Na tela Editar Atividade, clicar no botão Cancelar.

Resultado: Botão Cancelar não realiza nenhuma ação.

Resultado esperado: Cancelar edição e voltar para a lista de atividades.

**Comment by Johnnyx01** [comment]
Resolvido, tanto no cadastro quanto em editar a Atividade
